# Generated by Django 5.0.6 on 2024-05-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciepy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipy_name', models.CharField(max_length=100)),
                ('receipy_des', models.TextField()),
                ('receipy_img', models.ImageField(upload_to='receipeimage')),
            ],
        ),
    ]
